{
    "data": [
      {
        "content": "<p>The FastFRWD score is a comprehensive performance score that helps businesses assess their marketing success. It is based on four key metrics, Growth, Profitability, Acquisition, and Retention, to measure the performance of a business.</p><h2 style='color:#4049C2'> 1. Growth</h2><p>Growth measures the rate at which a business is growing, whether through increased sales or through expanding into new markets. There are multiple metrics that can be monitored when measuring growth: new users, revenue, traffic, etc. Our FastFRWD score specifically leverages growth in traffic as the key metric to assess growth.</p><h2 style='color:#4049C2'> 2. Profitability</h2><p>Profitability measures the ability of a business to acquire and retain customers profitably. At FastFRWD, we use LTV:CAC ratio as a key metric to assess profitability.</p><h2 style='color:#4049C2'> 3. Acquisition</h2><p>Acquisition measures how successful marketing efforts are at bringing in new customers. It looks at the mix and quality of paid, earned and owned traffic, as well as platform and tactic-level effectiveness.</p><h2 style='color:#4049C2'> 4. Retention</h2><p>Retention measures the ability of a business to drive repeat purchases and increase overall lifetime value of a customer. It is an important indicator of customer satisfaction, the quality of the products and services offered by the business, and how successful the business’ retention tactics are.</p>",
        "id": "fast-frwd-score",
        "introduction": "Comprehensive performance score based on four metrics: Growth, Profitability, Acquisition, and Retention.",
        "learn_category": "Metrics",
        "learn_more": [],
        "learn_more_available": false,
        "title": "FastFRWD Score"
      },
      {
        "content": "<p>Average Order Value (AOV) refers to the average dollar amount spent every time a customer places an order. To calculate Average Order Value, we divide total revenue by the total number of orders.</p><p>AOV is an important metric because it helps businesses understand buying behavior. It can help businesses understand pricing strategies, marketing effectiveness, performance of sales channels, and customer value..</p><p>For example, AOV can provide insights into the relative customer value derived from different marketing channels. By comparing the AOV of customers acquired through various channels, businesses can assess whether their marketing efforts on certain platforms are attracting customers with higher purchasing power. This information helps in making data-driven decisions about resource allocation and optimizing sales strategies to maximize profitability.</p><p>AOV can also be monitored in conjunction to ROAS, to measure the effectiveness of dollars spent to acquire customers in driving revenue from those customers.</p>",
        "fullform": "Average Order Value",
        "id": "aov",
        "introduction": "Measures customers’ spend. Refers to the average dollar amount spent every time a customer places an order.",
        "learn_category": "Metrics",
        "learn_more": [],
        "learn_more_available": false,
        "title": "AOV"
      },
      {
        "content": "<p>LTV:CAC (Lifetime Value to Customer Acquisition Cost) is a metric used to measure the return on investment of a company's sales and marketing efforts, by comparing the lifetime value of a customer to the cost of acquiring that customer.</p><p>The LTV:CAC ratio is one of the most widely used measures of how profitable a customer acquisition strategy is. It is made up of two parts:</p><ul><li><b>Lifetime Value (LTV)</b> the total profit generated by a given customer over the full lifetime of their relationship with the business.</li><li><b>Customer Acquisition Cost (CAC)</b> the initial cost of acquiring each new customer.</li></ul><p>The formula for calculating LTV to CAC is straightforward: divide LTV by CAC. This yields a value that indicates how much each customer adds to the business compared to how much it costs to obtain them.</p><ul><li>If this value is greater than 1, it means the revenue generated by a customer over time is greater than the cost to acquire them. This is (usually) good news!</li><li>Conversely, if this value is lower than 1, it means the cost to acquire the customer is higher than the revenue they will bring in. This unfortunately shows that acquiring new customers is unprofitable.</li></ul><p>The LTV:CAC ratio is important because it helps marketers make data-driven decisions and long-term plans on strategies and channels to prioritize as well as measure efficiency and profitability of customer acquisition efforts.</p>",
        "fullform": "Life Time Value : Costumer Acquisition Cost",
        "id": "ltv-cac",
        "introduction": "Ratio that measures how profitable a customer acquisition strategy is.",
        "learn_category": "Metrics",
        "learn_more": [
          {
            "fullform": "Life Time Value",
            "introduction": "Total profit generated by a given customer over the full lifetime of their relationship with the business.",
            "learn_category": "Metrics",
            "learn_more_id": "ltv",
            "learn_more_title": "LTV"
          },
          {
            "fullform": "Costumer Acquisition Cost",
            "introduction": "The initial cost to a business of acquiring each new customer.",
            "learn_category": "Metrics",
            "learn_more_id": "cac",
            "learn_more_title": "CAC"
          }
        ],
        "learn_more_available": true,
        "title": "LTV:CAC"
      },
      {
        "content": "<h2 style='color:#4049C2'>How is LTV calculated?</h2><p>Lifetime Value represents the total profit generated by a given customer over the full lifetime of their relationship with the business. When measuring LTV, calculations should ideally be based on variable contribution margin per customer. The LTV ideal ratio of 3:1 assumes LTV based on contribution margin. However, more basic calculations can be based on revenue only.</p><h2 style='color:#4049C2'>How does LTV inform decisions?</h2><p>LTV is an important metric because it helps businesses understand the long-term value of acquiring and retaining customers. Understanding LTV allows businesses to make marketing investment decisions, by helping them determine how much they are willing to pay on acquiring a new customer. It also allows businesses to understand the value of retaining customers. Businesses with high retention may choose to spend more marketing dollars to acquire a customer initially because they know they will recoup their investment over the duration of that customer’s lifetime.</p><p>LTV plays an important role in optimization of acquisition cost and marketing budget allocation. Businesses are able to prioritize channels and campaigns that attract customers with higher LTVs, and can adjust how much they are willing to spend on doing so.</p>",
        "fullform": "Life Time Value",
        "id": "ltv",
        "introduction": "Total profit generated by a given customer over the full lifetime of their relationship with the business.",
        "learn_category": "Metrics",
        "learn_more": [
          {
            "fullform": "Costumer Acquisition Cost",
            "introduction": "The initial cost to a business of acquiring each new customer.",
            "learn_category": "Metrics",
            "learn_more_id": "cac",
            "learn_more_title": "CAC"
          },
          {
            "fullform": "Life Time Value : Costumer Acquisition Cost",
            "introduction": "Ratio that measures how profitable a customer acquisition strategy is.",
            "learn_category": "Metrics",
            "learn_more_id": "ltv-cac",
            "learn_more_title": "LTV:CAC"
          }
        ],
        "learn_more_available": true,
        "title": "LTV"
      },
      {
        "content": "<p>Customer Acquisition Cost (CAC) is the initial cost of acquiring each new customer. To calculate CAC, businesses need to identify all of the costs associated with acquiring a customer during a specific period. This may include ad spend, content creation, sales salaries and commissions, etc. To obtain CAC, businesses divide the total of these costs by the number of unique new customers during the same period.</p><p>At FastFRWD we calculate a D2C e-commerce CAC by looking at the Working Spend we have access to as well as the Non-working and Working items you provide in the Spend page of our platform. That spend is then divided by the number of new customers acquired as defined by Shopify.</p><p>CAC is an important metric, because it allows businesses to understand how much they are spending to acquire each new customer, and make decisions about whether that cost is justified by the revenue generated.</p><p>Businesses use CAC to determine the appropriate level of investment in customer acquisition, compare the cost of acquiring customers across different marketing channels, and evaluate the effectiveness of their marketing and advertising campaigns.</p>",
        "fullform": "Costumer Acquisition Cost",
        "id": "cac",
        "introduction": "The initial cost to a business of acquiring each new customer.",
        "learn_category": "Metrics",
        "learn_more": [
          {
            "fullform": "Life Time Value",
            "introduction": "Total profit generated by a given customer over the full lifetime of their relationship with the business.",
            "learn_category": "Metrics",
            "learn_more_id": "ltv",
            "learn_more_title": "LTV"
          },
          {
            "fullform": "Life Time Value : Costumer Acquisition Cost",
            "introduction": "Ratio that measures how profitable a customer acquisition strategy is.",
            "learn_category": "Metrics",
            "learn_more_id": "ltv-cac",
            "learn_more_title": "LTV:CAC"
          }
        ],
        "learn_more_available": true,
        "title": "CAC"
      },
      {
        "content": "<p>Engagement Rate is a Google Analytics 4 (GA4) metric that measures user engagement on your brand’s website. It represents the percentage of visits that show meaningful engagement as measured in GA4. In GA4, an engaged session is defined as <b>lasting more than 10 seconds, having a conversion event, or featuring at least 2 page views.</b> Conversely, a bounce occurs when a session does not meet these criteria.</p><p>Understanding Engagement Rate is crucial for businesses. By examining specific channels, pages or screens, and marketing strategies, businesses can identify factors contributing to low engagement. They can optimize content, navigation, and design elements to encourage user engagement and improve overall site performance.</p><p>Engagement Rate is a useful metric to understand alongside Conversion Rate as it may provide valuable insights into user behavior and help identify potential bottlenecks in the conversion funnel.</p>",
        "id": "engagement-rate",
        "introduction": "Represents the percentage of visits that show meaningful engagement as measured in GA4.",
        "learn_category": "Metrics",
        "learn_more": [],
        "learn_more_available": false,
        "title": "Engagement Rate"
      },
      {
        "content": "<p>Paid, Earned, and Owned media are three different types of media channels used in marketing and communication strategies. Each type represents a different way of reaching and engaging with an audience.</p><h2 style='color:#53B2AD'>Paid Media</h2><p>Paid Media refers to the marketing channels that a brand pays for on a per placement basis. The key characteristic of Paid Media is that it requires a budget and is designed to reach a specific audience. Example channels include:</p><ul><li>Paid Search (e.g., Google Ads)</li><li>Paid Social (e.g., Meta Ads)</li></ul><h2 style='color:#53B2AD'>Earned Media</h2><p>Earned Media refers to the exposure that a brand receives organically without paying directly for the reach. The key characteristic of Earned Media is that it is unpaid and generated by others on behalf of the brand. Example channels include:</p><ul><li>Organic Search</li><li>Direct Traffic</li><li>Third-party Blogs</li><li>Product Reviews</li><li>Referrals</li></ul><h2 style='color:#53B2AD'>Owned Media</h2><p>Owned Media refers to the promotional tactics a brand may deploy within their own communication channels. Like paid channels, spend on owned channels may be based on reach. The distinction, however, is that users have opted-in to receive communication. The key characteristic of Owned Media is that it is under the direct control of the brand. Example channels include:</p><ul><li>Owned Social</li><li>E-mail (e.g., Klaviyo)</li><li>SMS (e.g., Attentive)",
        "fullform": "Paid,Earned,Owned Media",
        "id": "paid-earned-owned",
        "introduction": "Three different types of media channels used in marketing. Each represents a way of engaging with an audience.",
        "learn_category": "Channel",
        "learn_more": [],
        "learn_more_available": false,
        "title": "PEO"
      },
      {
        "content": "<p>Organic search traffic refers to the number of visitors who arrive at a website by clicking on a search engine result displayed based on the relevance of the content to a specific keyword or phrase. Organic search traffic is different from paid search traffic, which refers to the number of visitors who click on paid ads that are displayed alongside organic search results.</p><p>Google is an example of a search engine that generates organic search traffic for websites. When a user enters a search term on Google, the search engine's algorithm searches through its index of web pages to find the most relevant content. Google then displays these results on its search engine results page (SERP), with the most relevant results listed at the top. The more relevant and high-quality a website's content is, the more likely it is to rank high on the SERP and generate organic search traffic.</p><p>Organic search traffic is important for websites because it represents a significant source of free, high-quality traffic. This can lead to increased website traffic, higher engagement, conversions, and ultimately, revenue.</p>",
        "id": "organic-search",
        "introduction": "The number of visitors who arrive at a website by clicking on an organic search engine result.",
        "learn_category": "Channel",
        "learn_more": [
          {
            "introduction": "The number of visitors who arrive at a website through social media platforms, without any paid promotions.",
            "learn_category": "Channel",
            "learn_more_id": "organic-social",
            "learn_more_title": "Organic Social"
          }
        ],
        "learn_more_available": true,
        "title": "Organic Search"
      },
      {
        "content": "<p>Organic social traffic refers to the number of visitors who arrive at a website through social media platforms, without any paid promotions. This traffic is generated when a user sees a brand's social media post and clicks on a link to visit the brand's website.</p><p>Organic social traffic can come from a variety of platforms. Instagram and Facebook, owned by Meta, are two of the most common sources of organic social traffic. These platforms prioritize content that generates high engagement and interaction among users.</p><p>Organic social media traffic is an essential part of any successful social media strategy. It is a valuable source of engagement and brand awareness, which can lead to increased website traffic, higher conversion rates, and better ROI. Organic social traffic also needs to be monitored closely with respect to organic posts created by other users about the brand or the product. Brands should think about how the content in their own social channels can relate to what other people are saying about the brand on those channels.</p>",
        "id": "organic-social",
        "introduction": "The number of visitors who arrive at a website through social media platforms, without any paid promotions.",
        "learn_category": "Channel",
        "learn_more": [
          {
            "introduction": "The number of visitors who arrive at a website by clicking on an organic search engine result.",
            "learn_category": "Channel",
            "learn_more_id": "organic-search",
            "learn_more_title": "Organic Search"
          }
        ],
        "learn_more_available": true,
        "title": "Organic Social"
      },
      {
        "content": "<p>Direct traffic refers to traffic from visitors who come to a brand's website by typing a URL directly into their browser. This traffic typically comes from visitors who are familiar with the brand or have been referred to the brand's site through offline channels.</p><p>Direct traffic is important because it is a good indicator of a brand's recognition. If people know the brand, they are more likely to type the website URL directly into their browser.</p><p>Direct traffic can also have an impact on search engine rankings. People typing in a brand's URL directly into their browser can be an indication of brand relevance, which can improve search engine rankings.</p><p>An important disclaimer is that Direct traffic in Google Analytics can also refer to website visits where the traffic source is unknown or the referral source is not properly tracked. It is, therefore, important for brands to implement parameters and tracking codes to improve data accuracy.</p>",
        "id": "direct-traffic",
        "introduction": "Visitors who come to a brand's website by typing a URL directly into their browser or clicking on a bookmark.",
        "learn_category": "Channel",
        "learn_more": [
          {
            "introduction": "Visits obtained through a brand's e-mail marketing campaigns.",
            "learn_category": "Channel",
            "learn_more_id": "email-traffic",
            "learn_more_title": "E-mail Traffic"
          }
        ],
        "learn_more_available": true,
        "title": "Direct Traffic"
      },
      {
        "content": "<p>E-mail traffic refers to the visits obtained through your brand's e-mail marketing campaigns. Specifically, it refers to visitors who are directed to a brand's site after clicking on links within e-mails sent to subscribers and customers. E-mail traffic is important because it can tell brands how engaged their current leads and customers are.</p><p>There are a number of platforms that allow businesses to create and send e-mail campaigns to their subscribers: Klaviyo, Mailchimp, HubSpot, Campaign Monitor, among many others. Klaviyo is one of the most popular platforms that help businesses deploy, track, and analyze e-mail traffic.</p><p>Klaviyo offers a range of features including integration with e-commerce platforms, advanced automation features, A/B testing, and segmentation.</p>",
        "id": "email-traffic",
        "introduction": "Visits obtained through a brand's e-mail marketing campaigns.",
        "learn_category": "Channel",
        "learn_more": [
          {
            "introduction": "Visitors who come to a brand's website by typing a URL directly into their browser or clicking on a bookmark.",
            "learn_category": "Channel",
            "learn_more_id": "direct-traffic",
            "learn_more_title": "Direct Traffic"
          }
        ],
        "learn_more_available": true,
        "title": "E-mail Traffic"
      },
      {
        "content": "<p>Working spend refers to the amount spent on placing media and content in front of an audience. Specifically, it refers to the money spent on paid media channels.</p><p>Examples of working spend include paid advertising, including paid search, social media advertising and display advertising, and brand activation spend.</p><p>Working spend is important because it directly drives revenue growth. By optimizing working spend, businesses are able to optimize their ROI and ensure they are investing in the most effective strategies.</p>",
        "id": "working-spend",
        "introduction": "The amount spent on placing media and content on paid channels.",
        "learn_category": "Spend",
        "learn_more": [
          {
            "introduction": "The marketing budget that is not directly allocated to distributing content via paid media channels.",
            "learn_category": "Spend",
            "learn_more_id": "non-working-spend",
            "learn_more_title": "Non Working Spend"
          }
        ],
        "learn_more_available": true,
        "title": "Working Spend"
      },
      {
        "content": "<p>Non-working spend refers to the marketing budget that is not directly allocated to distributing marketing content via paid media channels. At FastFRWD, we specifically focus on the following types of non-working spend: Creative, Agency, Technology, Promotion, Other.</p><p>All spend related to earned and owned media is considered non-working spend, because none of it goes towards the distribution of content via paid media channels.</p><p>Non-working spend is important because it allows businesses to invest in the infrastructure needed to effectively run a marketing campaign. Non-working spend is what enables businesses to develop a deeper understanding of their audiences, build brand equity, and develop strategies to deliver long-term success. By carefully managing non-working spend, businesses can maximize the effectiveness of their ROI and marketing investments.</p><div style='border-left: 3px solid #F59B00;'><blockquote><p><i><b>\"Content is king in the world of marketing, but without the necessary non-working spend, even the best content can go unnoticed.\" - John Smith, Marketing Director.</b></i></p></blockquote></div>",
        "id": "non-working-spend",
        "introduction": "The marketing budget that is not directly allocated to distributing content via paid media channels.",
        "learn_category": "Spend",
        "learn_more": [
          {
            "introduction": "The amount spent on placing media and content on paid channels.",
            "learn_category": "Spend",
            "learn_more_id": "working-spend",
            "learn_more_title": "Working Spend"
          }
        ],
        "learn_more_available": true,
        "title": "Non Working Spend"
      }
    ]
  }